name: smart_popup
description: "A versatile Flutter alert dialog with videos, images, animations, countdown timer, and Loading state for buttons etc."
version: 1.0.9
homepage: https://github.com/fazil-kp/smart_popup.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_hooks: ^0.20.5
  flutter_timer_countdown: ^1.0.7
  video_player: ^2.9.1
  video_player_win: ^2.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
